trigger:
- none

pool:
  vmImage: 'ubuntu-latest'

variables:
  awsRegion: 'us-east-1'
  clusterName: 'KubernetsPractice'
  ecrRepo: '059948106103.dkr.ecr.us-east-1.amazonaws.com/kubernets/boardgame'
  imageTag: 'latest'

stages:
- stage: BuildAndPush
  displayName: "Build and Push Docker Image to ECR"
  jobs:
  - job: Build
    steps:
    - checkout: self

    # Install JDK 17 (compatible with Maven)
    - task: JavaToolInstaller@0
      inputs:
        versionSpec: '21'
        jdkArchitectureOption: 'x64'
        jdkSourceOption: 'PreInstalled'

    # Build JAR
    - task: Maven@3
      displayName: "Build JAR with Maven"
      inputs:
        mavenPomFile: 'pom.xml'
        goals: 'package'
        publishJUnitResults: false

    - task: SonarCloudPrepare@3
      inputs:
        SonarQube: 'SonarcubeAcess'
        organization: 'devopspracticeitt'
        scannerMode: 'cli'
        configMode: 'manual'
        cliProjectKey: 'devopspracticeitt'
        cliProjectName: 'DevOpsPracticeITT_Kubernets_Assignment'
        cliSources: '.'

    - task: SonarCloudAnalyze@3
      inputs:
        jdkversion: 'JAVA_HOME_21_X64'

    - task: SonarCloudPublish@3
      inputs:
        pollingTimeoutSec: '300'

    # Login to AWS ECR
    - task: AWSShellScript@1
      displayName: "Login to Amazon ECR"
      inputs:
        awsCredentials: 'aws-eks-connection'   # AWS service connection
        regionName: $(awsRegion)
        scriptType: 'inline'
        inlineScript: |
          aws ecr get-login-password --region $(awsRegion) | docker login --username AWS --password-stdin $(ecrRepo)

    # Build Docker image
    - script: |
        docker build -t $(ecrRepo):$(imageTag) .
      displayName: "Build Docker Image"

    # Push Docker image
    - script: |
        docker push $(ecrRepo):$(imageTag)
      displayName: "Push Docker Image to ECR"

- stage: Deploy
  displayName: "Deploy to EKS with kubectl"
  dependsOn: BuildAndPush
  jobs:
  - job: Deploy
    steps:
    - task: AWSShellScript@1
      displayName: "Configure kubeconfig and deploy"
      inputs:
        awsCredentials: 'aws-eks-connection'  # must be AWS service connection with EKSAdmin IAM user
        regionName: $(awsRegion)
        scriptType: 'inline'
        inlineScript: |
          # Generate kubeconfig for EKS
          aws eks update-kubeconfig --region $(awsRegion) --name $(clusterName)

          # Ensure kubectl uses the correct kubeconfig
          export KUBECONFIG=$HOME/.kube/config

          # Verify connectivity
          kubectl get nodes

          # Apply manifests
          kubectl apply -f deployment-service.yaml

